// WRAM ranges
const WRAM_START: u32 = 0x7E0000;
const WRAM_END: u32 = 0x7FFFFF;
const WRAM_RANGE: RangeInclusive<u32> = WRAM_START..=WRAM_END;

// PPU register ranges
const PPU_REGISTERS_START: u32 = 0x002100;
const PPU_REGISTERS_END: u32 = 0x00213F;
const PPU_REGISTERS_RANGE: angeInclusive<u32> = PPU_REGISTERS_START..=PPU_REGISTERS_END;

// APU register ranges
const APU_REGISTERS_START: u32 = 0x002140;
const APU_REGISTERS_END: u32 = 0x00217F;
const APU_REGISTERS_RANGE: RangeInclusive<u32> = APU_REGISTERS_START..=APU_REGISTERS_END;

// Cartridge ROM (LoROM example)
const CARTRIDGE_ROM_START: u32 = 0x008000;
const CARTRIDGE_ROM_END: u32 = 0x00FFFF;
const CARTRIDGE_ROM_RANGE: RangeInclusive<u32> = CARTRIDGE_ROM_START..=CARTRIDGE_ROM_END;
